=== 6--/pz-buildplanner/schema/mod.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Mod",
  "description": "A Project Zomboid Mod",
  "type": "object",
  "properties": {
    "id": {
      "description": "The ID of the mod",
      "type": "string"
    },
    "name": {
      "description": "The name of the mod",
      "type": "string"
    },
    "author": {
      "description": "The author/authors of the mod",
      "type": "string"
    },
    "requires": {
      "description": "A list of mod IDs who must be loaded alongside this one",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "incompatible": {
      "description": "A list of mod IDs who cannot be loaded alongside this one",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "workshop_id": {
      "type": "integer"
    },
    "shortcut": {
      "description": "A unique integer identifying this mod, used for preset urls",
      "type": "integer"
    },
    "traits": {
      "description": "A table of traits included in this mod",
      "type": "object",
      "additionalProperties": {
        "$ref": "../schema/trait.json"
      }
    },
    "professions": {
      "description": "A table of professions included in this mod",
      "type": "object",
      "additionalProperties": {
        "$ref": "../schema/profession.json"
      }
    },
    "mutual_exclusives": {
      "description": "A list of trait ID pairs indicating those which are mutually exclusive",
      "type": "array",
      "items": {
        "description": "A pair of trait IDs that will be mutually exclusive",
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 2,
        "maxItems": 2,
        "uniqueItems": true
      },
      "uniqueItems": true
    },
    "lang": {
      "description": "A table of language keys and their associated text",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "author",
    "shortcut",
    "traits",
    "professions",
    "mutual_exclusives",
    "lang"
  ]
}

=== 6--/pz-buildplanner/data/ScottyMoreTraits.json
{
  "id": "ScottyMoreTraits",
  "name": "Scotty's Additions: Traits",
  "author": "ScottyThePilot",
  "workshop_id": 3094590007,
  "shortcut": 11,
  "traits": {
    "SCT_Foolish": {
      "name_key": "UI_trait_SCT_Foolish",
      "description_key": "UI_trait_SCT_FoolishDesc",
      "shortcut": 469,
      "icon_path": "#/data/images/traits/scotty_additions/foolish.png",
      "cost": -1
    },
    "SCT_NervesOfSteel": {
      "name_key": "UI_trait_SCT_NervesOfSteel",
      "description_key": "UI_trait_SCT_NervesOfSteelDesc",
      "shortcut": 470,
      "icon_path": "#/data/images/traits/scotty_additions/nerves_of_steel.png",
      "cost": 5
    },
    "SCT_Worrywart": {
      "name_key": "UI_trait_SCT_Worrywart",
      "description_key": "UI_trait_SCT_WorrywartDesc",
      "shortcut": 471,
      "icon_path": "#/data/images/traits/scotty_additions/worrywart.png",
      "cost": -4
    }
  },
  "professions": {},
  "mutual_exclusives": [
    [
      "SCT_NervesOfSteel",
      "SCT_Worrywart"
    ],
    [
      "SCT_NervesOfSteel",
      "Smoker"
    ],
    [
      "Hemophobic",
      "SCT_NervesOfSteel"
    ],
    [
      "Desensitized",
      "SCT_Worrywart"
    ],
    [
      "Brave",
      "SCT_Worrywart"
    ],
    [
      "SCT_Worrywart",
      "Smoker"
    ],
    [
      "Hemophobic",
      "SCT_Worrywart"
    ],
    [
      "SCT_NervesOfSteel",
      "SOAlcoholic"
    ],
    [
      "SCT_Worrywart",
      "SOAlcoholic"
    ],
    [
      "Desensitized2",
      "SCT_Worrywart"
    ],
    [
      "MSTAlcoholic",
      "SCT_NervesOfSteel"
    ],
    [
      "MSTAlcoholic",
      "SCT_Worrywart"
    ],
    [
      "SCT_NervesOfSteel",
      "drinker"
    ],
    [
      "SCT_Worrywart",
      "drinker"
    ],
    [
      "SCT_Worrywart",
      "terminator"
    ]
  ],
  "lang": {
    "UI_trait_SCT_Foolish": "Foolish",
    "UI_trait_SCT_FoolishDesc": "Oh, what a fool you are.",
    "UI_trait_SCT_NervesOfSteel": "Nerves of Steel",
    "UI_trait_SCT_NervesOfSteelDesc": "Cannot become stressed.",
    "UI_trait_SCT_Worrywart": "Worrywart",
    "UI_trait_SCT_WorrywartDesc": "Becomes stressed when panicked.\n(When panicked, stress will increase to the same level as panic.)"
  }
}

=== 6--/pz-buildplanner/data/ScottyInjuryTraits.json
{
  "id": "ScottyInjuryTraits",
  "name": "Scotty's Additions: Injury Traits",
  "author": "ScottyThePilot",
  "workshop_id": 3094590007,
  "shortcut": 10,
  "traits": {
    "SCT_Injured": {
      "name_key": "UI_trait_SCT_Injured",
      "description_key": "UI_trait_SCT_InjuredDesc",
      "shortcut": 464,
      "icon_path": "#/data/images/traits/scotty_additions/injured.png",
      "cost": -2
    },
    "SCT_Burned": {
      "name_key": "UI_trait_SCT_Burned",
      "description_key": "UI_trait_SCT_BurnedDesc",
      "shortcut": 465,
      "icon_path": "#/data/images/traits/scotty_additions/burned.png",
      "cost": -5
    },
    "SCT_FractureArm": {
      "name_key": "UI_trait_SCT_FractureArm",
      "description_key": "UI_trait_SCT_FractureArmDesc",
      "shortcut": 466,
      "icon_path": "#/data/images/traits/scotty_additions/broken_arm.png",
      "cost": -6
    },
    "SCT_FractureLeg": {
      "name_key": "UI_trait_SCT_FractureLeg",
      "description_key": "UI_trait_SCT_FractureLegDesc",
      "shortcut": 467,
      "icon_path": "#/data/images/traits/scotty_additions/broken_leg.png",
      "cost": -8
    },
    "SCT_Bitten": {
      "name_key": "UI_trait_SCT_Bitten",
      "description_key": "UI_trait_SCT_BittenDesc",
      "shortcut": 468,
      "icon_path": "#/data/images/traits/scotty_additions/bitten.png",
      "cost": -20
    }
  },
  "professions": {},
  "mutual_exclusives": [
    [
      "SCT_Burned",
      "SCT_Injured"
    ],
    [
      "SCT_Bitten",
      "SCT_Injured"
    ],
    [
      "SCT_Bitten",
      "SCT_Burned"
    ],
    [
      "Bitten",
      "SCT_Bitten"
    ]
  ],
  "lang": {
    "UI_trait_SCT_Bitten": "Bitten",
    "UI_trait_SCT_BittenDesc": "Your days are numbered, what will you do?.\n(Starts with a bite on an arm, and is infected. Cannot be immune.)",
    "UI_trait_SCT_Burned": "Burned",
    "UI_trait_SCT_BurnedDesc": "Has received severe burns all over your body.\n(Starts with three burns on an arm, leg and your torso.)",
    "UI_trait_SCT_FractureArm": "Broken Arm",
    "UI_trait_SCT_FractureArmDesc": "What an unfortunate time to break your arm.\n(Starts with a random arm fracture.)",
    "UI_trait_SCT_FractureLeg": "Broken Leg",
    "UI_trait_SCT_FractureLegDesc": "What an unfortunate time to break your leg.\n(Starts with a random leg fracture.)",
    "UI_trait_SCT_Injured": "Injured",
    "UI_trait_SCT_InjuredDesc": "Has received moderate injuries.\n(Starts with three scratches or lacerations on an arm, leg and your torso.)"
  }
}
